---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: krishna8080/test1:1.0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: springpetclinic
      labels:
        app: krishna8080/test1:1.0
    spec:
      containers:
        - name: springpetclinic
          image: krishna8080/test1:1.0
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: springpetclinic
      port: 8080
      targetPort: 8080
